# Generated by Django 4.1 on 2022-08-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='saleitem',
            index_together={('id', 'slug')},
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to='product/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='picture',
            field=models.ImageField(upload_to='sale/%Y-%m-%d'),
        ),
    ]
