# Generated by Django 4.1 on 2022-08-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mailing_alter_userform_options_alter_userform_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
