# Generated by Django 4.1 on 2022-08-31 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='small_description',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
