# Generated by Django 4.1 on 2022-09-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_product_small_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomSlider',
        ),
    ]
