# Generated by Django 4.1 on 2022-09-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_userform_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userform',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
