# Generated by Django 4.1 on 2022-09-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_userform_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='price',
        ),
    ]
