# Generated by Django 4.1 on 2022-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_saleitem_price'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.AddField(
            model_name='product',
            name='position_by_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('position_by_id', 'slug')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
    ]
