# Generated by Django 4.1 on 2022-10-31 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_product_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
    ]
