# Generated by Django 4.1 on 2022-10-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_product_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='some_field',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
