# Generated by Django 4.1 on 2022-10-31 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_product_some_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='some_field',
        ),
    ]
