# Generated by Django 4.1 on 2022-11-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default=1, upload_to='product/%Y-%m-%d'),
            preserve_default=False,
        ),
    ]
