# Generated by Django 4.1 on 2022-11-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
