# Generated by Django 4.1 on 2022-11-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_product_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='position',
        ),
    ]
