# Generated by Django 4.1 on 2022-09-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_userorderform_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderform',
            name='order',
        ),
    ]
