# Generated by Django 4.1 on 2022-09-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_userorderform_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderform',
            name='order',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
