# Generated by Django 4.1 on 2022-09-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_userorderform_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderform',
            name='email',
            field=models.TextField(auto_created=True, default=1, max_length=400),
            preserve_default=False,
        ),
    ]
