# Generated by Django 4.1 on 2022-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_userorderform_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorderform',
            name='email',
            field=models.CharField(auto_created=True, max_length=400),
        ),
    ]
