# Generated by Django 4.1 on 2022-10-31 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_userorderform_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorderform',
            name='email',
        ),
    ]
